{
 "title": "Windhager",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Raumtemperatur Neubau",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "windhager.UMUMLZ.1_Neubau.Raumtemperatur.Aktueller_Wert"
    }
   ]
  },
  {
   "title": "Raumtemperatur Altbau",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "windhager.UMUMLZ.2_Altbau.Raumtemperatur.Aktueller_Wert"
    }
   ]
  },
  {
   "title": "Außentemperatur",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "windhager.UMUMLZ.1_Neubau.Aussentemperatur.Aussentemperatur"
    }
   ]
  },
  {
   "title": "Kesselleistung",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "windhager.BioWINII.BioWINII.Infoebene.Aktuelle_Kesselleistung"
    }
   ]
  },
  {
   "title": "Betriebsstunden",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "‎ h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "windhager.BioWINII.BioWINII.Infoebene.Betriebsstunden"
    }
   ]
  },
  {
   "title": "Zeit bis Hauptreinigung",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "‎ h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "windhager.BioWINII.BioWINII.Infoebene.Laufzeit_bis_Hauptreinigung"
    }
   ]
  },
  {
   "title": "Zeit bis Reinigung",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "‎ h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "windhager.BioWINII.BioWINII.Infoebene.Laufzeit_bis_Reinigung"
    }
   ]
  },
  {
   "title": "Zeit bis Wartung",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "‎ h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "windhager.BioWINII.BioWINII.Infoebene.Laufzeit_bis_Wartung"
    }
   ]
  },
  {
   "title": "Temperaturen",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "windhager.BioWINII.BioWINII.Titelbild.Kesseltemperatur_Istwert"
    },
    {
     "target": "windhager.UMUMLZ.1_Neubau.Warmwassertemperatur.Aktueller_Wert"
    },
    {
     "target": "windhager.WFBPK.Pufferspeicher_2000.Puffertemperaturen.TPA"
    },
    {
     "target": "windhager.WFBPK.Pufferspeicher_2000.Puffertemperaturen.TPE"
    },
    {
     "target": "windhager.UMUMLZ.1_Neubau.Vorlauftemperatur.Aktueller_Wert"
    }
   ]
  },
  {
   "title": "Kesselleistung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "target": "windhager.BioWINII.BioWINII.Infoebene.Aktuelle_Kesselleistung"
    }
   ]
  },
  {
   "title": "Brennerstarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "windhager.BioWINII.BioWINII.Infoebene.Anzahl_der_Brennerstarts"
    }
   ]
  },
  {
   "title": "Verbrauch seit Befüllung",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "windhager.BioWINII.BioWINII.Infoebene.Brennstoffverbrauch_seit_Befuellung"
    }
   ]
  },
  {
   "title": "Betriebsphase",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 21 },
   "targets": [
    {
     "target": "windhager.BioWINII.BioWINII.Titelbild.Betriebsphasen"
    }
   ]
  },
  {
   "title": "Verbrauch insgesamt",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "windhager.BioWINII.BioWINII.Infoebene.Brennstoffverbrauch_gesamt"
    }
   ]
  }
 ]
}